site_name: UPPMAX Workshop

nav:
  - Start: index.md
  - Uppmax Intro: 
    - UPPMAX: uppmax_intro/uppmax.md
    - High-Performance Computing (HPC): uppmax_intro/hpc.md
    - NAISS: uppmax_intro/naiss.md
    - Login procedure: uppmax_intro/login.md
    - Workflow: uppmax_intro/work.md
    - Module System (LMOD): uppmax_intro/module_system.md
    - SLURM: uppmax_intro/slurm.md
  - Python: 
    - Load and run: python/load_and_run.md
    - Packages: python/packages.md
    - Virtual Environments: python/venv.md
    - GPU example: python/gpu.md
  - Development Tools:
      - Jupyter: tools/jupyter.md
      - VSCode: tools/vscode.md

theme:
  name: material
  greetings: Welcome to UPPMAX userguide
  font:
    # text: Lato
    code: JetBrains Mono

  logo: assets/logo.svg

  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - content.code.annotate
    - content.tabs.link

  custom_dir: mkdocs_uppmax/

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - tables
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
   - plantuml:
        puml_url: https://www.plantuml.com/plantuml/
        num_workers: 8
